"""new structure to accomodate joining a team

Revision ID: 5e59753eb9fe
Revises: 844175032b03
Create Date: 2026-04-19 14:27:19.895655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e59753eb9fe'
down_revision = '844175032b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_team_membership_team_user', ['team_id', 'user_id'])

    with op.batch_alter_table('vault_keys', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_vault_key_team_user', ['team_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_keys', schema=None) as batch_op:
        batch_op.drop_constraint('uq_vault_key_team_user', type_='unique')

    with op.batch_alter_table('team_memberships', schema=None) as batch_op:
        batch_op.drop_constraint('uq_team_membership_team_user', type_='unique')

    # ### end Alembic commands ###
