"""updated db to have teams hold the secrets instead of individual vaults

Revision ID: 844175032b03
Revises: 70db8318a16e
Create Date: 2026-04-19 13:17:31.989605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '844175032b03'
down_revision = '70db8318a16e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    dialect_name = op.get_bind().dialect.name

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('env_blob', sa.Text(), nullable=True))

    with op.batch_alter_table('vault_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=False))
        if dialect_name != 'sqlite':
            batch_op.drop_constraint(batch_op.f('vault_keys_vault_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key('fk_vault_keys_team_id_teams', 'teams', ['team_id'], ['id'])
        batch_op.drop_column('vault_id')

    op.drop_table('secrets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vault_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vault_keys_vault_id_fkey'), 'secrets', ['vault_id'], ['id'])
        batch_op.drop_column('team_id')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('env_blob')

    op.create_table('secrets',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('encrypted_blob', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('secrets_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('secrets_pkey'))
    )
    # ### end Alembic commands ###
